# Generated by Django 2.2.2 on 2019-06-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotemodel',
            name='author',
            field=models.CharField(default='nick', max_length=500),
            preserve_default=False,
        ),
    ]
